// Code generated by _schema/schema_gen.go, DO NOT EDIT.

package wycheproof

// wycheproofVersion is the github.com/c2sp/wycheproof module version that
// schema.go was generated against.
const wycheproofVersion = "v0.0.0-20260625212325-ee7b4f7e6119"
